//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order.Repository
{
    using Order.Repository.DomainModel;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class SiriusIQEntities2 : DbContext
    {
        public SiriusIQEntities2()
            : base("name=SiriusIQEntities2")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CATEGORY> CATEGORies { get; set; }
        public DbSet<Member> Members { get; set; }
        public DbSet<MemberClaim> MemberClaims { get; set; }
        public DbSet<MemberLogin> MemberLogins { get; set; }
        public DbSet<ORDER> ORDERs { get; set; }
        public DbSet<ORDERDETAIL> ORDERDETAILs { get; set; }
        public DbSet<PRODUCT> PRODUCTs { get; set; }
        public DbSet<REVIEW> REVIEWs { get; set; }
        public DbSet<Role> Roles { get; set; }
    
        public virtual System.Data.Entity.Core.Objects.ObjectResult<GetProductDetails_Result> GetProductDetails(Nullable<int> productID)
        {
            var productIDParameter = productID.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("productID", productID) :
                new System.Data.Entity.Core.Objects.ObjectParameter("productID", typeof(int));
            var objectparamArray = new System.Data.Entity.Core.Objects.ObjectParameter[] { productIDParameter };
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductDetails_Result>("GetProductDetails", objectparamArray);
        }

        public virtual System.Data.Entity.Core.Objects.ObjectResult<GetProducts_Result> GetProducts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProducts_Result>("GetProducts");
        }
    }
}
