//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order.Repository
{
    using System;

    public partial class ORDERDETAIL
    {
        public int ORDERDETAILID { get; set; }
        public int ORDERID { get; set; }
        public int PRODUCTID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
    
        public virtual ORDER ORDER { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
