//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public PRODUCT()
        {
            this.ORDERDETAILs = new HashSet<ORDERDETAIL>();
            this.REVIEWs = new HashSet<REVIEW>();
        }
    
        public int PRODUCTID { get; set; }
        public Nullable<int> CATEGORYID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string Brand { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual ICollection<ORDERDETAIL> ORDERDETAILs { get; set; }
        public virtual ICollection<REVIEW> REVIEWs { get; set; }
    }
}
